---
- name: Get Installed Firmware Inventory
  hosts: idrac
  gather_facts: false

  tasks:
    - name: Get Installed Firmware Inventory.
      dellemc.openmanage.idrac_firmware_info:
        idrac_ip: "192.168.1.99"
        idrac_user: "root"
        idrac_password: "Root123."
      delegate_to: localhost