---
- name: Get Installed Firmware Inventory
  hosts: idrac
  gather_facts: false

  tasks:
    - name: Get Installed Firmware Inventory.
      dellemc.openmanage.idrac_firmware_info:
        idrac_ip: "{{ host }}"
        idrac_user: "{{ username }}"
        idrac_password: "{{ password }}"
      delegate_to: localhost